config_file		= [ space ] *( server [ space ] )

server			= "server" [ space ] "{" *( server_rule | both_rule | location )
					[ space ] "}" [ space ] .

location		= "location" space path space "{" *[ both_rule|location_rule ]
					[ space ] "}" [ space ] .

server_rule		= [ space ] ( r_listen | r_server_name )
					[ space ] ";" .

location_rule	= [ space ] ( r_root | r_method | r_index | r_upload_enable
					| r_upload_path | r_autoindex | r_cgi_ext | r_cgi_path )
					[ space ] ";" .

both_rule		= [ space ] ( r_max_size | r_error_page ) [ space ] ";" .

r_listen		= "listen" space port space ip_address .

r_server_name	= "server_name" 1*( space name ) .

r_error_page	= "error_page" space 3number space path .

r_root			= "root" space path space .

r_method		= "method" space 1*method_name .

r_index			= "index" space path .

r_upload_enable	= "upload_enable" space toggle .

r_upload_path	= "upload_path" space path .

r_autoindex		= "autoindex" space toggle .

r_cgi_ext		= "cgi_ext" space extension .

r_cgi_path		= "cgi_path" space path .

r_max_size		= "client_max_body_size" space 1*( number ) size .

method_name		=  "GET" | "HEAD" | "POST" | "PUT" | "DELETE"
					| "CONNECT" | "OPTIONS" | "TRACE" | "PATCH" 

path			= ( rel_path | abs_path ) [ extension ] .

rel_path		= "." [ sub_directory ] .

abs_path		= "/" directory [ sub_directory ] .

sub_directory	= *[ "/" directory ] [ "/" ] .

directory		= 1*character .		; a directory can be a file name

extension		= "." 1*character .

toggle			= "on" | "off"

character		= ; not defined yet

space			= 1*( SPACE | TAB | NEWLINE | comment ) .

comment			= "#" *character NEWLINE
